package com.livevoiceapp;

import android.content.Context;

import androidx.test.ext.junit.runners.AndroidJUnit4;
import androidx.test.platform.app.InstrumentationRegistry;

import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.webrtc.DataChannel;
import org.webrtc.MediaConstraints;
import org.webrtc.PeerConnection;
import org.webrtc.PeerConnectionFactory;
import org.webrtc.SdpObserver;
import org.webrtc.SessionDescription;

import java.util.Collections;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicReference;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;

/**
 * Device regression coverage for the native WebRTC startup path used by live.ts.
 *
 * <p>This deliberately uses no configured endpoint, ICE server, microphone, or
 * camera. Creating a peer connection and an in-band data channel is enough to
 * initialize libjingle's network monitor and exercise the same SDP path before
 * the app opens its realtime session.</p>
 */
@RunWith(AndroidJUnit4.class)
public final class WebRtcPeerConnectionInstrumentationTest {
    private static final long CALLBACK_TIMEOUT_SECONDS = 15L;
    private static PeerConnectionFactory factory;

    @BeforeClass
    public static void initializeWebRtc() {
        Context context = InstrumentationRegistry.getInstrumentation().getTargetContext();
        PeerConnectionFactory.initialize(
                PeerConnectionFactory.InitializationOptions.builder(context)
                        .createInitializationOptions());
        factory = PeerConnectionFactory.builder().createPeerConnectionFactory();
        assertNotNull("WebRTC factory should be created from the packaged native library", factory);
    }

    @AfterClass
    public static void disposeWebRtc() {
        if (factory != null) {
            factory.dispose();
            factory = null;
        }
    }

    @Test
    public void storageMigrationImplementationIsPackaged() throws Exception {
        // This class is generated by Room/KSP and must survive a fresh release build.
        assertNotNull(Class.forName("org.asyncstorage.legacy_storage.StorageDb_Impl"));
    }

    @Test
    public void createsDataChannelOfferAndReleasesPeerThreeTimes() throws Exception {
        assertNotNull(factory);

        for (int attempt = 0; attempt < 3; attempt++) {
            PeerConnection peer = null;
            DataChannel dataChannel = null;
            try {
                PeerConnection.RTCConfiguration configuration =
                        new PeerConnection.RTCConfiguration(
                                Collections.<PeerConnection.IceServer>emptyList());
                configuration.sdpSemantics = PeerConnection.SdpSemantics.UNIFIED_PLAN;
                configuration.enableImplicitRollback = true;

                peer = factory.createPeerConnection(configuration, new NoopPeerObserver());
                assertNotNull("PeerConnection creation must reach the native network monitor", peer);

                dataChannel = peer.createDataChannel("oai-events", new DataChannel.Init());
                assertNotNull("The realtime transport data channel should be creatable", dataChannel);

                SessionDescription offer = createOffer(peer);
                assertNotNull(offer);
                assertEquals(SessionDescription.Type.OFFER, offer.type);
                setLocalDescription(peer, offer);

                SessionDescription localDescription = peer.getLocalDescription();
                assertNotNull(localDescription);
                assertEquals(SessionDescription.Type.OFFER, localDescription.type);
            } finally {
                disposePeer(peer, dataChannel);
            }
        }
    }

    private static SessionDescription createOffer(PeerConnection peer) throws Exception {
        AtomicReference<SessionDescription> result = new AtomicReference<>();
        AtomicReference<String> failure = new AtomicReference<>();
        CountDownLatch done = new CountDownLatch(1);

        peer.createOffer(new SdpObserver() {
            @Override
            public void onCreateSuccess(SessionDescription description) {
                result.set(description);
                done.countDown();
            }

            @Override
            public void onSetSuccess() {
                // Not used for createOffer.
            }

            @Override
            public void onCreateFailure(String error) {
                failure.set(error == null ? "createOffer failed" : error);
                done.countDown();
            }

            @Override
            public void onSetFailure(String error) {
                // Not used for createOffer.
            }
        }, new MediaConstraints());

        assertTrue(
                "createOffer did not complete within the device test timeout",
                done.await(CALLBACK_TIMEOUT_SECONDS, TimeUnit.SECONDS));
        assertNull("createOffer must not fail", failure.get());
        return result.get();
    }

    private static void setLocalDescription(PeerConnection peer, SessionDescription offer)
            throws Exception {
        AtomicReference<String> failure = new AtomicReference<>();
        CountDownLatch done = new CountDownLatch(1);

        peer.setLocalDescription(new SdpObserver() {
            @Override
            public void onCreateSuccess(SessionDescription description) {
                // Not used for setLocalDescription.
            }

            @Override
            public void onSetSuccess() {
                done.countDown();
            }

            @Override
            public void onCreateFailure(String error) {
                // Not used for setLocalDescription.
            }

            @Override
            public void onSetFailure(String error) {
                failure.set(error == null ? "setLocalDescription failed" : error);
                done.countDown();
            }
        }, offer);

        assertTrue(
                "setLocalDescription did not complete within the device test timeout",
                done.await(CALLBACK_TIMEOUT_SECONDS, TimeUnit.SECONDS));
        assertNull("setLocalDescription must not fail", failure.get());
    }

    private static void disposePeer(PeerConnection peer, DataChannel dataChannel) {
        if (dataChannel != null) {
            dataChannel.close();
            dataChannel.dispose();
        }
        if (peer != null) {
            peer.close();
            peer.dispose();
        }
    }

    private static final class NoopPeerObserver implements PeerConnection.Observer {
        @Override
        public void onSignalingChange(PeerConnection.SignalingState state) {}

        @Override
        public void onIceConnectionChange(PeerConnection.IceConnectionState state) {}

        @Override
        public void onIceConnectionReceivingChange(boolean receiving) {}

        @Override
        public void onIceGatheringChange(PeerConnection.IceGatheringState state) {}

        @Override
        public void onIceCandidate(org.webrtc.IceCandidate candidate) {}

        @Override
        public void onIceCandidatesRemoved(org.webrtc.IceCandidate[] candidates) {}

        @Override
        public void onAddStream(org.webrtc.MediaStream stream) {}

        @Override
        public void onRemoveStream(org.webrtc.MediaStream stream) {}

        @Override
        public void onDataChannel(DataChannel channel) {}

        @Override
        public void onRenegotiationNeeded() {}
    }
}
